// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJzqWGd23CMRKXK6R_yQGUVWmwE9noMQY',
    appId: '1:565896366678:web:b4130ef368ed3b867049f7',
    messagingSenderId: '565896366678',
    projectId: 'messmanager-6ecaf',
    authDomain: 'messmanager-6ecaf.firebaseapp.com',
    storageBucket: 'messmanager-6ecaf.appspot.com',
    measurementId: 'G-YRW3Q8H4Z2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHIG4UL9djt-uQnAFaS9_Iny5esaS43Vw',
    appId: '1:565896366678:android:5ce1e2b232bcaf787049f7',
    messagingSenderId: '565896366678',
    projectId: 'messmanager-6ecaf',
    storageBucket: 'messmanager-6ecaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzpeMvAGllWVBVwaic28fzdjfRwukJt0M',
    appId: '1:565896366678:ios:1a2b25b82aa303a67049f7',
    messagingSenderId: '565896366678',
    projectId: 'messmanager-6ecaf',
    storageBucket: 'messmanager-6ecaf.appspot.com',
    iosBundleId: 'com.example.messmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzpeMvAGllWVBVwaic28fzdjfRwukJt0M',
    appId: '1:565896366678:ios:7a7fb3a95b49e7147049f7',
    messagingSenderId: '565896366678',
    projectId: 'messmanager-6ecaf',
    storageBucket: 'messmanager-6ecaf.appspot.com',
    iosBundleId: 'com.example.messmanager.RunnerTests',
  );
}
